# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d99701dfcd3a49c1780c81226d549b9"
name = "local-live-fabric-scanner-app"
application_url = "https://example.com/app/fabric-scanner-system"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/updated"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_products,write_inventory,write_merchant_managed_fulfillment_orders,write_products"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[app_proxy]
url = "https://example.com/app/fabric-scanner-system/api/proxy"
subpath = "fabric-scanner"
prefix = "apps"
